import re
import os
import logging
import re
import sys
import warnings
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable, Literal, Optional

import numpy as np
from datasets import Dataset, concatenate_datasets, load_dataset
from langdetect import DetectorFactory
from math_verify import parse, verify
from openai import OpenAI
from pyexpat.errors import messages
from tqdm import tqdm
from transformers import PreTrainedTokenizerBase

from src.utils import extract_boxed, process_ans, extract_tf

DetectorFactory.seed = 0
logging.getLogger("openai").setLevel(logging.WARNING)
logging.getLogger("openai._base_client").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)

from src.data.base import MixedUpDataset, Mixup

FilterRules = Literal[
    "none",  # no filtering
    "model_pos",  # keep all with >0 positives of model
    "model_pair",  # keep all with >0 positives and >0 negatives of model
    "pair",  # keep all with >0 positives and >0 negatives
    "double_model_pair",  # keep all with >1 positives and >1 negatives of model
    "double_pair",  # keep all with >1 positives and >1 negatives
]

VERIFICATION_PROMPT = (
    "Below is a problem statement, expected answer, and solution generated by an LLM.\n"
    "Determine whether the generated final answer is correct. Answer 'true' if it is correct, and 'false' otherwise.\n"
    "The reference answer and the answer to be judged only need to be essentially the same, ignoring irrelevant details such as units, symbols, whether or not to approximate, and the form of expression in the answer."
    "The two answers are considered to be consistent if they are equivalently transformable.\n\n"
    "[Problem Statement]\n{problem_statement}\n\n"
    "[Expected Answer]\n{solution}\n\n"
    "[Generated Solution]\n{proposed_solution}\n\n"
    "Now, evaluate the generated final answer.\n"
)

VERIFICATION_WITHOUT_GT_PROMPT = (
    "Below is a problem statement and solution generated by an LLM.\n"
    "Determine whether the generated final answer is correct. Answer 'true' if it is correct, and 'false' otherwise.\n"
    "[Problem Statement]\n{problem_statement}\n\n"
    "[Generated Solution]\n{proposed_solution}\n\n"
    "Now, evaluate the generated final answer.\n"
)

# NOTE I considered different format from the actual QA like <judge></judge>, but the verifier still wraps its decision with boxed{}
# WITH_COT = "Please reason step by step, and put your final answer within <judge></judge>, i.e., <judge>true</judge> or <judge>false</judge>."
WITH_COT = "Please reason step by step, and put your final answer within \\boxed{}, i.e., \\boxed{true} or \\boxed{false}"
WITHOUT_COT = "Do not provide any explanation, and put your answer within \\boxed{}, i.e., \\boxed{true} or \\boxed{false}"


class LightR1(MixedUpDataset):

    PROMPT = "Please reason step by step, and put your final answer within \\boxed{}."

    def __init__(
        self,
        name: str,
        tokenizer: PreTrainedTokenizerBase,
        mixup: Mixup,
        shuffle: bool = True,
        max_length: int = 1024,
        generating_model: str = "deepseek-ai/DeepSeek-R1",
        filter_rule: FilterRules = "model_pos",
        dataset_type: str = "sft",
        # below are for LLM-based verifier
        verifier: str = None,
        port: int = 8000,
        api_key: str = "null",
        verifier_max_tokens: Optional[int] = None,
        verifier_temperature: float = 0.7,
        verifier_with_gt: bool = False,
        verifier_enable_thinking: bool = True,
        verifier_cot: bool = False,
        sort_key: str = None,
        filter_key: str = None,
    ) -> None:
        super().__init__(name, tokenizer, mixup, shuffle, max_length)
        self.filter_rule = filter_rule
        self.generating_model = generating_model
        self.verifier = verifier
        self.port = port
        self.api_key = api_key
        self.verifier_max_tokens = verifier_max_tokens
        self.verifier_temperature = verifier_temperature
        self.verifier_with_gt = verifier_with_gt
        self.verifier_enable_thinking = verifier_enable_thinking
        self.verifier_cot = verifier_cot
        self.sort_key = sort_key
        self.filter_key = filter_key
        self.num_proc = os.cpu_count() // 2
        # NOTE: if we need completely different processing for SFT/DPOData, define separate classes.
        # `dataset_type` indicates in which stage the dataset is used for LighR1 paper, and does not correspond to our training recipe.
        path = "qihoo360/Light-R1-SFTData"
        self.raw_dataset = load_dataset(path, split="train")
        self.raw_dataset = (
            self.raw_dataset.shuffle() if self.shuffle else self.raw_dataset
        )

        if self.sort_key is not None:
            if self.sort_key in self.raw_dataset.column_names:
                self.raw_dataset = self.raw_dataset.sort(self.sort_key, reverse=True)
            else:
                warnings.warn(f"{self.sort_key} not in {self.raw_dataset.column_names}")
        if self.filter_key is not None:
            # remove 0-pass samples
            if self.filter_key in self.raw_dataset.column_names:
                self.raw_dataset = self.raw_dataset.filter(
                    lambda x: x[self.filter_key] > 0,
                    num_proc=self.num_proc,
                    keep_in_memory=True,
                    load_from_cache_file=False,
                )
            else:
                warnings.warn(
                    f"{self.filter_key} not in {self.raw_dataset.column_names}"
                )

        self.raw_dataset = self.raw_dataset.filter(
            self._filter_by_rule,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
            desc="Filtering dataset by rule: " + self.filter_rule,
        )
        self.mixup.set_confusion_matrix(n_samples=len(self.raw_dataset))

    def _filter_by_rule(self, example: dict) -> bool:
        """
        Filter examples based on the specified filtering rule.
        Args:
            example (dict): A dictionary containing the example data with 'positives' and 'negatives' keys.
                           Each positive/negative is expected to have a 'model' field.
        Returns:
            bool: True if the example passes the filter rule, False otherwise.
        Filter Rules:
            - "none": Accept all examples
            - "model_pos": Accept examples that have positives from the generating model
            - "model_pair": Accept examples that have both positives and negatives from the generating model
            - "pair": Accept examples that have both positives and negatives (any model)
            - "double_model_pair": Accept examples with multiple positives and negatives from the generating model
            - "double_pair": Accept examples with multiple positives and negatives from any model
        """
        if self.filter_rule == "none":
            return True
        elif self.filter_rule == "model_pos":
            return any(
                p["model"] == self.generating_model for p in example["positives"]
            )
        elif self.filter_rule == "model_pair":
            return any(
                p["model"] == self.generating_model for p in example["positives"]
            ) and any(n["model"] == self.generating_model for n in example["negatives"])
        elif self.filter_rule == "pair":
            return len(example["positives"]) > 0 and len(example["negatives"]) > 0
        elif self.filter_rule == "double_model_pair":
            return (
                sum(p["model"] == self.generating_model for p in example["positives"])
                > 1
                and sum(
                    n["model"] == self.generating_model for n in example["negatives"]
                )
                > 1
            )
        elif self.filter_rule == "double_pair":
            return len(example["positives"]) > 1 and len(example["negatives"]) > 1

    def _to_messages(self, example: dict) -> list[dict[str, str]]:
        return {
            "proc_messages": [
                {
                    "role": "user",
                    "content": example["conversations"][0]["value"]
                    + f"\n{self.PROMPT}",
                },
                {"role": "assistant", "content": example["conversations"][1]["value"]},
            ]
        }

    def prepare_for_sft(self) -> Dataset:
        """
        Takes the dataset and returns it already tokenized, ready for SFT training. It mixes up
        the labels in order to achieve the mixup specified in the Mixup object.
        """

        n_pos = self.mixup.TP
        n_neg = self.mixup.FP

        if n_pos > 0:
            pos_set = self.raw_dataset.select(range(n_pos)).remove_columns(
                ["negatives"]
            )
        else:
            pos_set = self.raw_dataset.select([]).remove_columns(["negatives"])
        if n_neg > 0:
            neg_set = self.raw_dataset.select(
                range(n_pos, n_pos + n_neg)
            ).remove_columns(["positives"])
        else:
            neg_set = self.raw_dataset.select([]).remove_columns(["positives"])

        def tokenize_function(example: dict, negative: bool = False) -> dict:
            marker = "negatives" if negative else "positives"
            if "model" in self.filter_rule:
                options = [
                    option
                    for option in example[marker]
                    if option["model"] == self.generating_model
                ]
            else:
                options = example[marker]
            if len(options) == 0:
                raise ValueError(
                    f"""
                    No {marker} completions found for this example. Perhaps you set the filtering
                    rule wrong. If negatives are needed, make sure that you set either pair, or
                    double_pair rules.
                    """
                )
            idx_option = np.random.randint(0, len(options))
            prompt = example["prompt"] + f"\n{self.PROMPT}"
            target_reasoning, target_final_ans = (
                options[idx_option]["reasoning"],
                options[idx_option]["final_answer"],
            )
            target = f"<think>\n{target_reasoning}\n</think>\n{target_final_ans}"
            messages = [
                {"role": "user", "content": prompt},
                {"role": "assistant", "content": target},
            ]
            return self.tokenizer.apply_chat_template(
                messages,
                tokenize=True,
                return_dict=True,
                max_length=self.max_length,
                padding="max_length",
            )

        pos_set = pos_set.map(
            tokenize_function,
            fn_kwargs={"negative": False},
            batched=False,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
        )
        pos_set = pos_set.remove_columns(
            [
                c
                for c in pos_set.column_names
                if c not in ["input_ids", "attention_mask"]
            ]
        )

        neg_set = neg_set.map(
            tokenize_function,
            fn_kwargs={"negative": True},
            batched=False,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
        )
        neg_set = neg_set.remove_columns(
            [
                c
                for c in neg_set.column_names
                if c not in ["input_ids", "attention_mask"]
            ]
        )

        mixed_dataset = concatenate_datasets([pos_set, neg_set]).shuffle()
        del pos_set, neg_set
        mixed_dataset = mixed_dataset.map(
            lambda x: {"labels": x["input_ids"]},
            batched=False,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
        )

        mixed_dataset = mixed_dataset.filter(
            lambda x: len(x["input_ids"]) <= self.max_length,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
        )
        return mixed_dataset

    def prepare_for_distil(self) -> None:
        raise NotImplementedError()

    def prepare_for_dpo(self) -> None:
        raise NotImplementedError()

    def prepare_for_ppo(self) -> None:
        raise NotImplementedError()

    def prepare_for_grpo(self) -> tuple[Dataset, Callable]:

        # NOTE: ideally, this trimmed dataset should have EXACTLY the same prompts as what
        # you get with the same configuration from the offline SFT dataset. this can be
        # currently achieved if you first call the offline SFT created, but this is wasteful.
        # something smarter has to be implemented. also keep in mind that the offline setting
        # might not even make it to the paper, as it is bleeding from a million wounds. so
        # let's see what the future of all this will be.
        trimmed_dataset = self.raw_dataset.remove_columns(
            [c for c in self.raw_dataset.column_names if c not in ["prompt", "answer"]]
        )
        convert_to_message_format = lambda example: {
            "prompt": [
                {"role": "user", "content": example["prompt"] + f"\n{self.PROMPT}"}
            ],
        }
        trimmed_dataset = trimmed_dataset.map(
            convert_to_message_format,
            batched=False,
            num_proc=self.num_proc,
            keep_in_memory=True,
            load_from_cache_file=False,
        )

        def reward(
            completions: list[list[dict[str, str]]],
            answer: list[str],  # be careful that the name is 'answer' singular
            prompts: list[list[dict[str, str]]],
            **kwargs,
        ) -> list[float]:
            items = [
                {
                    "question": prompt[0]["content"],
                    "answer": ans,
                    "completion_full": completion[0]["content"],
                    "completion_extracted": extract_boxed(completion[0]["content"]),
                }
                for prompt, ans, completion in zip(prompts, answer, completions)
            ]

            def _rule_based_verification(
                completions: list[list[dict[str, str]]], answer: list[str]
            ) -> list[float]:
                # Extract final answers (if any) and build extractability mask
                output_list = [completion[0]["content"] for completion in completions]
                extracted_list = [extract_boxed(content) for content in output_list]

                # Process extracted answers for math verification
                completions_processed = [parse(process_ans(e)) for e in extracted_list]
                answers_processed = [parse(process_ans(ans)) for ans in answer]

                # Ground-truth verification (True/False per completion)
                gt_verification = [
                    verify(completion, ans)
                    for completion, ans in zip(completions_processed, answers_processed)
                ]
                return gt_verification

            def _llm_based_verification(
                completions: list[list[dict[str, str]]],
                answer: list[str],
                prompts: list[list[dict[str, str]]],
            ) -> list[float]:

                def _single_call(client, model_name, prompt, ans, completion):
                    # if completion is not extractable, immediately return false
                    if not extract_boxed(completion[0]["content"]):
                        return "false"
                    if self.verifier_with_gt:
                        message_content = VERIFICATION_PROMPT.format(
                            problem_statement=prompt[0]["content"],
                            solution=ans,
                            proposed_solution=completion[0]["content"],
                        )
                    else:
                        message_content = VERIFICATION_WITHOUT_GT_PROMPT.format(
                            problem_statement=prompt[0]["content"],
                            proposed_solution=completion[0]["content"],
                        )
                    if self.verifier_cot:
                        message_content += WITH_COT
                    else:
                        message_content += WITHOUT_COT
                    request_kwargs = {
                        "model": model_name,
                        "messages": [
                            {
                                "role": "user",
                                "content": message_content,
                            },
                        ],
                        "temperature": self.verifier_temperature,
                        "seed": 42,
                        "extra_body": {
                            "chat_template_kwargs": {
                                "enable_thinking": self.verifier_enable_thinking
                            }
                        },
                    }

                    response = client.chat.completions.create(**request_kwargs)
                    return response

                client = OpenAI(
                    api_key=self.api_key,
                    base_url=f"http://localhost:{self.port}/v1",
                    timeout=300,
                )

                llm_verification = [False] * len(completions)
                verifier_reasoning = [None] * len(completions)
                verifier_cot = [None] * len(completions)
                with ThreadPoolExecutor(max_workers=32) as executor:
                    futures = {
                        executor.submit(
                            _single_call,
                            client,
                            self.verifier,
                            prompt,
                            ans,
                            completion,
                        ): idx
                        for idx, (prompt, ans, completion) in enumerate(
                            zip(prompts, answer, completions)
                        )
                    }
                    for future in tqdm(
                        as_completed(futures), total=len(futures), leave=False
                    ):
                        idx = futures[future]
                        try:
                            response = future.result()
                            # _single_call may return a plain string ("false") for
                            # non-extractable completions. Handle both string and
                            # OpenAI-style response objects robustly.
                            if isinstance(response, str):
                                content = response.strip().lower()
                            else:
                                content = (
                                    response.choices[0].message.content.strip().lower()
                                )
                                if hasattr(response.choices[0].message, "reasoning") and response.choices[0].message.reasoning is not None:
                                    verifier_reasoning[idx] = (
                                        response.choices[0]
                                        .message.reasoning.strip()
                                        .replace("\n", "[LF]")
                                    )
                                else:
                                    match = re.search(
                                        r"<think>(.*?)</think>",
                                        content,
                                        flags=re.DOTALL,
                                    )
                                    if match:
                                        verifier_reasoning[idx] = (
                                            match.group(1).strip().replace("\n", "[LF]")
                                        )

                            match = re.search(
                                r"<think>(.*?)</think>",
                                content,
                                flags=re.DOTALL,
                            )
                            if match:
                                verifier_cot[idx] = match.group(1).strip().replace("\n", "[LF]")
                            # extract final decision
                            output = re.sub(
                                r"<think>.*?</think>",
                                "",
                                content,
                                flags=re.DOTALL,
                            ).strip()
                            decision = extract_tf(output)
                            if idx == 0:
                                print(f"Verification result example:\n{content[:50].replace('\n', ' ')}...{content[-50:].replace('\n', ' ')}")
                            if decision == "true":
                                llm_verification[idx] = True
                            elif decision == "false":
                                llm_verification[idx] = False
                            else:
                                print(
                                    f"Unexpected verification decision for completion {idx}: {decision.replace('\\n', ' ')}"
                                )
                                # best effort - if it contains only one of "true" or "false", reuturn that
                                if "true" in output and "false" not in output:
                                    llm_verification[idx] = True
                                elif "true" not in output and "false" in output:
                                    llm_verification[idx] = False

                                llm_verification[idx] = False  # or handle as needed

                        except Exception as e:

                            def _truncate(s: str, max_len: int = 100) -> str:
                                return re.sub(r"[\r\n]+", " ", str(s))[:max_len]

                            prompt_print = _truncate(prompts[idx][0]["content"])
                            completion_print = _truncate(completions[idx][0]["content"])
                            print(
                                f"Error processing completion {idx}: {e}"
                                f"prompt={prompt_print},"
                                f"answer={answer[idx]},"
                                f"completion(len={len(completions[idx][0]['content'])})={completion_print}..."
                            )
                            llm_verification[idx] = False  # or handle as needed

                reward._verifier_reasoning = verifier_reasoning
                reward._verifier_cot = verifier_cot
                return llm_verification

            if self.verifier is None:
                gt_verification = _rule_based_verification(completions, answer)
                # store for logging
                reward._oracle_rewards = gt_verification
                reward._gt_answers = answer
                reward._extracted_answers = [
                    extract_boxed(completion[0]["content"])
                    for completion in completions
                ]
                return self.mixup.mixup_rewards(
                    gt_verification,
                    items=items,
                )
            else:
                gt_verification = _rule_based_verification(completions, answer)
                llm_verification = _llm_based_verification(completions, answer, prompts)
                # store for logging
                reward._oracle_rewards = gt_verification
                reward._gt_answers = answer
                reward._extracted_answers = [
                    extract_boxed(completion[0]["content"])
                    for completion in completions
                ]
                return self.mixup.mixup_rewards(
                    llm_verification,
                    items=items,
                    oracle_rewards=gt_verification,
                )

        return trimmed_dataset, reward
